// =============================================================================
// playoffs.js — Source of truth for NHL Playoff series data
// =============================================================================
// Generated by admin.html on 5/1/2026, 1:07:58 AM.
// Replace this file in the GitHub repo to update live prices.
// =============================================================================

const PLAYOFFS_DATA = {
  "generatedAt": "2026-05-01T07:07:58.580Z",
  "generatedBy": "admin.html",
  "bracket": {
    "east": {
      "r1": [
        "e1-atl-1v4",
        "e1-atl-2v3",
        "e1-met-1v4",
        "e1-met-2v3"
      ],
      "r2": [
        "e2-atl-final",
        "e2-met-final"
      ],
      "r3": "e3-conference-final"
    },
    "west": {
      "r1": [
        "w1-cen-1v4",
        "w1-cen-2v3",
        "w1-pac-1v4",
        "w1-pac-2v3"
      ],
      "r2": [
        "w2-cen-final",
        "w2-pac-final"
      ],
      "r3": "w3-conference-final"
    },
    "final": "scf"
  },
  "bracketConnections": {
    "e2-atl-final": {
      "topFrom": "e1-atl-1v4",
      "botFrom": "e1-atl-2v3"
    },
    "e2-met-final": {
      "topFrom": "e1-met-1v4",
      "botFrom": "e1-met-2v3"
    },
    "w2-cen-final": {
      "topFrom": "w1-cen-1v4",
      "botFrom": "w1-cen-2v3"
    },
    "w2-pac-final": {
      "topFrom": "w1-pac-1v4",
      "botFrom": "w1-pac-2v3"
    },
    "e3-conference-final": {
      "topFrom": "e2-atl-final",
      "botFrom": "e2-met-final"
    },
    "w3-conference-final": {
      "topFrom": "w2-cen-final",
      "botFrom": "w2-pac-final"
    },
    "scf": {
      "topFrom": "e3-conference-final",
      "botFrom": "w3-conference-final"
    }
  },
  "series": {
    "e1-atl-1v4": {
      "label": "Atlantic 1 vs Wild Card 1",
      "conference": "East",
      "round": 1,
      "topSeed": {
        "name": "Buffalo Sabres",
        "short": "BUF"
      },
      "botSeed": {
        "name": "Boston Bruins",
        "short": "BOS"
      },
      "mode": "manual",
      "auto": {
        "topHomeWinPct": 0.55,
        "botHomeWinPct": 0.5
      },
      "manual": {
        "game1": 0.55,
        "game2": 0.55,
        "game3": 0.5,
        "game4": 0.5,
        "game5": 0.55,
        "game6": 0.5,
        "game7": 0.55
      },
      "state": {
        "topWins": 3,
        "botWins": 2,
        "history": [
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            1,
            1
          ],
          [
            2,
            1
          ],
          [
            3,
            1
          ],
          [
            3,
            2
          ]
        ]
      },
      "margin": {}
    },
    "e1-atl-2v3": {
      "label": "Atlantic 2 vs Atlantic 3",
      "conference": "East",
      "round": 1,
      "topSeed": {
        "name": "Tampa Bay Lightning",
        "short": "TBL"
      },
      "botSeed": {
        "name": "Montreal Canadiens",
        "short": "MTL"
      },
      "mode": "manual",
      "auto": {
        "topHomeWinPct": 0.55,
        "botHomeWinPct": 0.5
      },
      "manual": {
        "game1": 0.5614,
        "game2": 0.5614,
        "game3": 0.48140000000000005,
        "game4": 0.48140000000000005,
        "game5": 0.5614,
        "game6": 0.48140000000000005,
        "game7": 0.5614
      },
      "state": {
        "topWins": 2,
        "botWins": 3,
        "history": [
          [
            0,
            0
          ],
          [
            0,
            1
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ]
        ]
      },
      "margin": {}
    },
    "e1-met-1v4": {
      "label": "Metropolitan 1 vs Wild Card 2",
      "conference": "East",
      "round": 1,
      "topSeed": {
        "name": "Carolina Hurricanes",
        "short": "CAR"
      },
      "botSeed": {
        "name": "Ottawa Senators",
        "short": "OTT"
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.6,
        "botHomeWinPct": 0.45
      },
      "manual": {
        "game1": 0.6,
        "game2": 0.6,
        "game3": 0.55,
        "game4": 0.55,
        "game5": 0.6,
        "game6": 0.55,
        "game7": 0.6
      },
      "state": {
        "topWins": 4,
        "botWins": 0,
        "history": [
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            2,
            0
          ],
          [
            3,
            0
          ],
          [
            4,
            0
          ]
        ]
      },
      "margin": {}
    },
    "e1-met-2v3": {
      "label": "Metropolitan 2 vs Metropolitan 3",
      "conference": "East",
      "round": 1,
      "topSeed": {
        "name": "Pittsburgh Penguins",
        "short": "PIT"
      },
      "botSeed": {
        "name": "Philadelphia Flyers",
        "short": "PHI"
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.55,
        "botHomeWinPct": 0.5
      },
      "manual": {
        "game1": 0.55,
        "game2": 0.55,
        "game3": 0.5,
        "game4": 0.5,
        "game5": 0.55,
        "game6": 0.5,
        "game7": 0.55
      },
      "state": {
        "topWins": 2,
        "botWins": 4,
        "history": [
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            2,
            4
          ]
        ]
      },
      "margin": {}
    },
    "w1-cen-1v4": {
      "label": "Central 1 vs Wild Card 2",
      "conference": "West",
      "round": 1,
      "topSeed": {
        "name": "Colorado Avalanche",
        "short": "COL"
      },
      "botSeed": {
        "name": "Los Angeles Kings",
        "short": "LAK"
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.62,
        "botHomeWinPct": 0.45
      },
      "manual": {
        "game1": 0.62,
        "game2": 0.62,
        "game3": 0.55,
        "game4": 0.55,
        "game5": 0.62,
        "game6": 0.55,
        "game7": 0.62
      },
      "state": {
        "topWins": 4,
        "botWins": 0,
        "history": [
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            2,
            0
          ],
          [
            3,
            0
          ],
          [
            4,
            0
          ]
        ]
      },
      "margin": {}
    },
    "w1-cen-2v3": {
      "label": "Central 2 vs Central 3",
      "conference": "West",
      "round": 1,
      "topSeed": {
        "name": "Dallas Stars",
        "short": "DAL"
      },
      "botSeed": {
        "name": "Minnesota Wild",
        "short": "MIN"
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.55,
        "botHomeWinPct": 0.5
      },
      "manual": {
        "game1": 0.55,
        "game2": 0.55,
        "game3": 0.5,
        "game4": 0.5,
        "game5": 0.55,
        "game6": 0.5,
        "game7": 0.55
      },
      "state": {
        "topWins": 2,
        "botWins": 4,
        "history": [
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            2,
            4
          ]
        ]
      },
      "margin": {}
    },
    "w1-pac-1v4": {
      "label": "Pacific 1 vs Wild Card 1",
      "conference": "West",
      "round": 1,
      "topSeed": {
        "name": "Vegas Golden Knights",
        "short": "VGK"
      },
      "botSeed": {
        "name": "Utah Mammoth",
        "short": "UTA"
      },
      "mode": "manual",
      "auto": {
        "topHomeWinPct": 0.6,
        "botHomeWinPct": 0.48
      },
      "manual": {
        "game1": 0.5838,
        "game2": 0.5838,
        "game3": 0.5038,
        "game4": 0.5038,
        "game5": 0.5838,
        "game6": 0.5038,
        "game7": 0.5838
      },
      "state": {
        "topWins": 3,
        "botWins": 2,
        "history": [
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            3,
            2
          ]
        ]
      },
      "margin": {}
    },
    "w1-pac-2v3": {
      "label": "Pacific 2 vs Pacific 3",
      "conference": "West",
      "round": 1,
      "topSeed": {
        "name": "Edmonton Oilers",
        "short": "EDM"
      },
      "botSeed": {
        "name": "Anaheim Ducks",
        "short": "ANA"
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.55,
        "botHomeWinPct": 0.5
      },
      "manual": {
        "game1": 0.55,
        "game2": 0.55,
        "game3": 0.5,
        "game4": 0.5,
        "game5": 0.55,
        "game6": 0.5,
        "game7": 0.55
      },
      "state": {
        "topWins": 2,
        "botWins": 4,
        "history": [
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            2,
            4
          ]
        ]
      },
      "margin": {}
    },
    "e2-atl-final": {
      "label": "Atlantic Final",
      "conference": "East",
      "round": 2,
      "topSeed": {
        "name": "",
        "short": ""
      },
      "botSeed": {
        "name": "",
        "short": ""
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.5,
        "botHomeWinPct": 0.5
      },
      "manual": {
        "game1": 0.5,
        "game2": 0.5,
        "game3": 0.5,
        "game4": 0.5,
        "game5": 0.5,
        "game6": 0.5,
        "game7": 0.5
      },
      "state": {
        "topWins": 0,
        "botWins": 0,
        "history": [
          [
            0,
            0
          ]
        ]
      },
      "margin": {}
    },
    "e2-met-final": {
      "label": "Metropolitan Final",
      "conference": "East",
      "round": 2,
      "topSeed": {
        "name": "Carolina Hurricanes",
        "short": "CAR"
      },
      "botSeed": {
        "name": "Philadelphia Flyers",
        "short": "PHI"
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.58,
        "botHomeWinPct": 0.48
      },
      "manual": {
        "game1": 0.58,
        "game2": 0.58,
        "game3": 0.52,
        "game4": 0.52,
        "game5": 0.58,
        "game6": 0.52,
        "game7": 0.58
      },
      "state": {
        "topWins": 0,
        "botWins": 0,
        "history": [
          [
            0,
            0
          ]
        ]
      },
      "margin": {}
    },
    "w2-cen-final": {
      "label": "Central Final",
      "conference": "West",
      "round": 2,
      "topSeed": {
        "name": "Colorado Avalanche",
        "short": "COL"
      },
      "botSeed": {
        "name": "Minnesota Wild",
        "short": "MIN"
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.6,
        "botHomeWinPct": 0.48
      },
      "manual": {
        "game1": 0.6,
        "game2": 0.6,
        "game3": 0.52,
        "game4": 0.52,
        "game5": 0.6,
        "game6": 0.52,
        "game7": 0.6
      },
      "state": {
        "topWins": 0,
        "botWins": 0,
        "history": [
          [
            0,
            0
          ]
        ]
      },
      "margin": {}
    },
    "w2-pac-final": {
      "label": "Pacific Final",
      "conference": "West",
      "round": 2,
      "topSeed": {
        "name": "",
        "short": ""
      },
      "botSeed": {
        "name": "Anaheim Ducks",
        "short": "ANA"
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.55,
        "botHomeWinPct": 0.5
      },
      "manual": {
        "game1": 0.55,
        "game2": 0.55,
        "game3": 0.5,
        "game4": 0.5,
        "game5": 0.55,
        "game6": 0.5,
        "game7": 0.55
      },
      "state": {
        "topWins": 0,
        "botWins": 0,
        "history": [
          [
            0,
            0
          ]
        ]
      },
      "margin": {}
    },
    "e3-conference-final": {
      "label": "Eastern Conference Final",
      "conference": "East",
      "round": 3,
      "topSeed": {
        "name": "",
        "short": ""
      },
      "botSeed": {
        "name": "",
        "short": ""
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.5,
        "botHomeWinPct": 0.5
      },
      "manual": {
        "game1": 0.5,
        "game2": 0.5,
        "game3": 0.5,
        "game4": 0.5,
        "game5": 0.5,
        "game6": 0.5,
        "game7": 0.5
      },
      "state": {
        "topWins": 0,
        "botWins": 0,
        "history": [
          [
            0,
            0
          ]
        ]
      },
      "margin": {}
    },
    "w3-conference-final": {
      "label": "Western Conference Final",
      "conference": "West",
      "round": 3,
      "topSeed": {
        "name": "",
        "short": ""
      },
      "botSeed": {
        "name": "",
        "short": ""
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.5,
        "botHomeWinPct": 0.5
      },
      "manual": {
        "game1": 0.5,
        "game2": 0.5,
        "game3": 0.5,
        "game4": 0.5,
        "game5": 0.5,
        "game6": 0.5,
        "game7": 0.5
      },
      "state": {
        "topWins": 0,
        "botWins": 0,
        "history": [
          [
            0,
            0
          ]
        ]
      },
      "margin": {}
    },
    "scf": {
      "label": "Stanley Cup Final",
      "conference": "Final",
      "round": 4,
      "topSeed": {
        "name": "",
        "short": ""
      },
      "botSeed": {
        "name": "",
        "short": ""
      },
      "mode": "derived",
      "auto": {
        "topHomeWinPct": 0.5,
        "botHomeWinPct": 0.5
      },
      "manual": {
        "game1": 0.5,
        "game2": 0.5,
        "game3": 0.5,
        "game4": 0.5,
        "game5": 0.5,
        "game6": 0.5,
        "game7": 0.5
      },
      "state": {
        "topWins": 0,
        "botWins": 0,
        "history": [
          [
            0,
            0
          ]
        ]
      },
      "margin": {}
    }
  },
  "defaults": {
    "margin": {
      "seriesWinner": 0.05,
      "correctScore": 0.08,
      "totalGamesOU": 0.05,
      "totalGamesExact": 0.08,
      "spreads": 0.05,
      "afterG3": 0.06,
      "afterG4": 0.06,
      "fromBehindNeverTrail": 0.06,
      "conferenceWinner": 0.1,
      "stanleyCupWinner": 0.15,
      "outrightSchedule": {
        "1": {
          "conference": 0.1,
          "stanleyCup": 0.16
        },
        "2": {
          "conference": 0.08,
          "stanleyCup": 0.12
        },
        "3": {
          "conference": 0.045,
          "stanleyCup": 0.08
        },
        "4": {
          "conference": 0.045,
          "stanleyCup": 0.045
        }
      }
    }
  },
  "outrightBiases": {
    "eastConf": {
      "CAR": -0.005
    },
    "westConf": {
      "COL": 0.01
    },
    "scf": {
      "COL": 0.01,
      "CAR": -0.005
    }
  },
  "outrightBlend": {
    "eastConf": {
      "enabled": true,
      "marketWeight": 0.7,
      "fanDuelText": "\nCarolina Hurricanes\n+100\nMontreal Canadiens\n+500\nBuffalo Sabres\n+550\nPhiladelphia Flyers\n+700\nTampa Bay Lightning\n+700\nBoston Bruins\n+3000",
      "draftKingsText": "CAR Hurricanes\n+105\n\nBUF Sabres\n+400\n\nMTL Canadiens\n+600\n\nTB Lightning\n+800\n\nPHI Flyers\n+800\n\nBOS Bruins\n+3500",
      "fanDuelProbs": {
        "CAR": 0.5,
        "MTL": 0.16666666666666666,
        "BUF": 0.15384615384615385,
        "PHI": 0.125,
        "TBL": 0.125,
        "BOS": 0.03225806451612903
      },
      "draftKingsProbs": {
        "CAR": 0.4878048780487805,
        "BUF": 0.2,
        "MTL": 0.14285714285714285,
        "TBL": 0.1111111111111111,
        "PHI": 0.1111111111111111,
        "BOS": 0.027777777777777776
      }
    },
    "westConf": {
      "enabled": true,
      "marketWeight": 0.7,
      "fanDuelText": "Colorado Avalanche\n-105\nVegas Golden Knights\n+380\nAnaheim Ducks\n+650\nMinnesota Wild\n+410\nUtah Mammoth\n+2200",
      "draftKingsText": "COL Avalanche\n+105\n\nVGK Golden Knights\n+300\n\nMIN Wild\n+425\n\nANA Ducks\n+850\n\nUTA Mammoth\n+2200\n",
      "fanDuelProbs": {
        "COL": 0.5121951219512195,
        "VGK": 0.20833333333333334,
        "ANA": 0.13333333333333333,
        "MIN": 0.19607843137254902,
        "UTA": 0.043478260869565216
      },
      "draftKingsProbs": {
        "COL": 0.4878048780487805,
        "VGK": 0.25,
        "MIN": 0.19047619047619047,
        "ANA": 0.10526315789473684,
        "UTA": 0.043478260869565216
      }
    },
    "scf": {
      "enabled": true,
      "marketWeight": 0.7,
      "fanDuelText": "Colorado Avalanche\n+220\nCarolina Hurricanes\n+270\nVegas Golden Knights\n+900\nMinnesota Wild\n+950\nMontreal Canadiens\n+1200\nBuffalo Sabres\n+1300\nTampa Bay Lightning\n+1300\nAnaheim Ducks\n+1700\nPhiladelphia Flyers\n+1700\nUtah Mammoth\n+5000\nBoston Bruins\n+8000",
      "draftKingsText": "COL Avalanche\n+210\n\nCAR Hurricanes\n+230\n\nVGK Golden Knights\n+700\n\nMIN Wild\n+950\n\nBUF Sabres\n+1000\n\nMTL Canadiens\n+1500\n\nTB Lightning\n+1600\n\nPHI Flyers\n+2500\n\nANA Ducks\n+2500\n\nUTA Mammoth\n+6000\n\nBOS Bruins\n+10000",
      "fanDuelProbs": {
        "COL": 0.3125,
        "CAR": 0.2702702702702703,
        "VGK": 0.1,
        "MIN": 0.09523809523809523,
        "MTL": 0.07692307692307693,
        "BUF": 0.07142857142857142,
        "TBL": 0.07142857142857142,
        "ANA": 0.05555555555555555,
        "PHI": 0.05555555555555555,
        "UTA": 0.0196078431372549,
        "BOS": 0.012345679012345678
      },
      "draftKingsProbs": {
        "COL": 0.3225806451612903,
        "CAR": 0.30303030303030304,
        "VGK": 0.125,
        "MIN": 0.09523809523809523,
        "BUF": 0.09090909090909091,
        "MTL": 0.0625,
        "TBL": 0.058823529411764705,
        "PHI": 0.038461538461538464,
        "ANA": 0.038461538461538464,
        "UTA": 0.01639344262295082,
        "BOS": 0.009900990099009901
      }
    }
  }
};

// Attach to window so other script tags can access it.
if (typeof window !== 'undefined') {
  window.PLAYOFFS_DATA = PLAYOFFS_DATA;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = PLAYOFFS_DATA;
}
