// =============================================================================
// playoffs.js — Source of truth for NHL Playoff series data
// =============================================================================
// Generated by admin.html. Replace this file in the repo to update live prices.
// =============================================================================

const PLAYOFFS_DATA = {
  generatedAt: "2026-04-30T00:00:00Z",
  generatedBy: "manual-bootstrap",

  // --- Bracket structure (NHL post-2014 no-reseed format) ---
  // Each round's series IDs are listed in the order they should appear in the bracket.
  bracket: {
    east: {
      r1: ["e1-atl-1v4", "e1-atl-2v3", "e1-met-1v4", "e1-met-2v3"],
      r2: ["e2-atl-final", "e2-met-final"],
      r3: "e3-conference-final"
    },
    west: {
      r1: ["w1-cen-1v4", "w1-cen-2v3", "w1-pac-1v4", "w1-pac-2v3"],
      r2: ["w2-cen-final", "w2-pac-final"],
      r3: "w3-conference-final"
    },
    final: "scf"
  },

  // --- How winners feed forward ---
  // For each downstream series, define which prior series feed the top and bottom slots.
  // 'topFromSeed' / 'botFromSeed' indicates which seed (1 or 2) becomes top/bottom in next round
  // by default; admin tool offers override.
  bracketConnections: {
    "e2-atl-final":         { topFrom: "e1-atl-1v4", botFrom: "e1-atl-2v3" },
    "e2-met-final":         { topFrom: "e1-met-1v4", botFrom: "e1-met-2v3" },
    "w2-cen-final":         { topFrom: "w1-cen-1v4", botFrom: "w1-cen-2v3" },
    "w2-pac-final":         { topFrom: "w1-pac-1v4", botFrom: "w1-pac-2v3" },
    "e3-conference-final":  { topFrom: "e2-atl-final", botFrom: "e2-met-final" },
    "w3-conference-final":  { topFrom: "w2-cen-final", botFrom: "w2-pac-final" },
    "scf":                  { topFrom: "e3-conference-final", botFrom: "w3-conference-final" }
  },

  // --- Series data ---
  // Each series carries everything needed to price it.
  // Empty teams (name = "") indicate the series isn't filled yet (waiting on prior round).
  series: {
    // ===== EAST ROUND 1 =====
    "e1-atl-1v4": {
      label: "Atlantic 1 vs Wild Card 2",
      conference: "East",
      round: 1,
      topSeed: { name: "Maple Leafs", short: "TOR" },
      botSeed: { name: "Senators",    short: "OTT" },
      mode: "auto",
      auto: { topHomeWinPct: 0.55, botHomeWinPct: 0.50 },
      manual: { game1: 0.55, game2: 0.55, game3: 0.50, game4: 0.50, game5: 0.55, game6: 0.50, game7: 0.55 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },
    "e1-atl-2v3": {
      label: "Atlantic 2 vs Atlantic 3",
      conference: "East",
      round: 1,
      topSeed: { name: "Lightning", short: "TBL" },
      botSeed: { name: "Panthers",  short: "FLA" },
      mode: "auto",
      auto: { topHomeWinPct: 0.50, botHomeWinPct: 0.55 },
      manual: { game1: 0.50, game2: 0.50, game3: 0.45, game4: 0.45, game5: 0.50, game6: 0.45, game7: 0.50 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },
    "e1-met-1v4": {
      label: "Metropolitan 1 vs Wild Card 1",
      conference: "East",
      round: 1,
      topSeed: { name: "Capitals",  short: "WSH" },
      botSeed: { name: "Canadiens", short: "MTL" },
      mode: "auto",
      auto: { topHomeWinPct: 0.62, botHomeWinPct: 0.45 },
      manual: { game1: 0.62, game2: 0.62, game3: 0.55, game4: 0.55, game5: 0.62, game6: 0.55, game7: 0.62 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },
    "e1-met-2v3": {
      label: "Metropolitan 2 vs Metropolitan 3",
      conference: "East",
      round: 1,
      topSeed: { name: "Hurricanes", short: "CAR" },
      botSeed: { name: "Devils",     short: "NJD" },
      mode: "auto",
      auto: { topHomeWinPct: 0.62, botHomeWinPct: 0.48 },
      manual: { game1: 0.62, game2: 0.62, game3: 0.52, game4: 0.52, game5: 0.62, game6: 0.52, game7: 0.62 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },

    // ===== WEST ROUND 1 =====
    "w1-cen-1v4": {
      label: "Central 1 vs Wild Card 2",
      conference: "West",
      round: 1,
      topSeed: { name: "Jets",  short: "WPG" },
      botSeed: { name: "Blues", short: "STL" },
      mode: "auto",
      auto: { topHomeWinPct: 0.62, botHomeWinPct: 0.45 },
      manual: { game1: 0.62, game2: 0.62, game3: 0.55, game4: 0.55, game5: 0.62, game6: 0.55, game7: 0.62 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },
    "w1-cen-2v3": {
      label: "Central 2 vs Central 3",
      conference: "West",
      round: 1,
      topSeed: { name: "Stars",     short: "DAL" },
      botSeed: { name: "Avalanche", short: "COL" },
      mode: "auto",
      auto: { topHomeWinPct: 0.50, botHomeWinPct: 0.55 },
      manual: { game1: 0.50, game2: 0.50, game3: 0.45, game4: 0.45, game5: 0.50, game6: 0.45, game7: 0.50 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },
    "w1-pac-1v4": {
      label: "Pacific 1 vs Wild Card 1",
      conference: "West",
      round: 1,
      topSeed: { name: "Knights", short: "VGK" },
      botSeed: { name: "Wild",    short: "MIN" },
      mode: "auto",
      auto: { topHomeWinPct: 0.60, botHomeWinPct: 0.48 },
      manual: { game1: 0.60, game2: 0.60, game3: 0.52, game4: 0.52, game5: 0.60, game6: 0.52, game7: 0.60 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },
    "w1-pac-2v3": {
      label: "Pacific 2 vs Pacific 3",
      conference: "West",
      round: 1,
      topSeed: { name: "Kings",  short: "LAK" },
      botSeed: { name: "Oilers", short: "EDM" },
      mode: "auto",
      auto: { topHomeWinPct: 0.52, botHomeWinPct: 0.55 },
      manual: { game1: 0.52, game2: 0.52, game3: 0.45, game4: 0.45, game5: 0.52, game6: 0.45, game7: 0.52 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },

    // ===== EAST ROUND 2 (waiting on R1) =====
    "e2-atl-final": {
      label: "Atlantic Final",
      conference: "East",
      round: 2,
      topSeed: { name: "", short: "" },
      botSeed: { name: "", short: "" },
      mode: "auto",
      auto: { topHomeWinPct: 0.50, botHomeWinPct: 0.50 },
      manual: { game1: 0.50, game2: 0.50, game3: 0.50, game4: 0.50, game5: 0.50, game6: 0.50, game7: 0.50 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },
    "e2-met-final": {
      label: "Metropolitan Final",
      conference: "East",
      round: 2,
      topSeed: { name: "", short: "" },
      botSeed: { name: "", short: "" },
      mode: "auto",
      auto: { topHomeWinPct: 0.50, botHomeWinPct: 0.50 },
      manual: { game1: 0.50, game2: 0.50, game3: 0.50, game4: 0.50, game5: 0.50, game6: 0.50, game7: 0.50 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },

    // ===== WEST ROUND 2 =====
    "w2-cen-final": {
      label: "Central Final",
      conference: "West",
      round: 2,
      topSeed: { name: "", short: "" },
      botSeed: { name: "", short: "" },
      mode: "auto",
      auto: { topHomeWinPct: 0.50, botHomeWinPct: 0.50 },
      manual: { game1: 0.50, game2: 0.50, game3: 0.50, game4: 0.50, game5: 0.50, game6: 0.50, game7: 0.50 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },
    "w2-pac-final": {
      label: "Pacific Final",
      conference: "West",
      round: 2,
      topSeed: { name: "", short: "" },
      botSeed: { name: "", short: "" },
      mode: "auto",
      auto: { topHomeWinPct: 0.50, botHomeWinPct: 0.50 },
      manual: { game1: 0.50, game2: 0.50, game3: 0.50, game4: 0.50, game5: 0.50, game6: 0.50, game7: 0.50 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },

    // ===== CONFERENCE FINALS =====
    "e3-conference-final": {
      label: "Eastern Conference Final",
      conference: "East",
      round: 3,
      topSeed: { name: "", short: "" },
      botSeed: { name: "", short: "" },
      mode: "auto",
      auto: { topHomeWinPct: 0.50, botHomeWinPct: 0.50 },
      manual: { game1: 0.50, game2: 0.50, game3: 0.50, game4: 0.50, game5: 0.50, game6: 0.50, game7: 0.50 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },
    "w3-conference-final": {
      label: "Western Conference Final",
      conference: "West",
      round: 3,
      topSeed: { name: "", short: "" },
      botSeed: { name: "", short: "" },
      mode: "auto",
      auto: { topHomeWinPct: 0.50, botHomeWinPct: 0.50 },
      manual: { game1: 0.50, game2: 0.50, game3: 0.50, game4: 0.50, game5: 0.50, game6: 0.50, game7: 0.50 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    },

    // ===== STANLEY CUP FINAL =====
    "scf": {
      label: "Stanley Cup Final",
      conference: "Final",
      round: 4,
      topSeed: { name: "", short: "" },
      botSeed: { name: "", short: "" },
      mode: "auto",
      auto: { topHomeWinPct: 0.50, botHomeWinPct: 0.50 },
      manual: { game1: 0.50, game2: 0.50, game3: 0.50, game4: 0.50, game5: 0.50, game6: 0.50, game7: 0.50 },
      state: { topWins: 0, botWins: 0, history: [[0,0]] },
      margin: {}
    }
  },

  defaults: {
    margin: {
      seriesWinner: 0.05,
      correctScore: 0.08,
      totalGamesOU: 0.05,
      totalGamesExact: 0.08,
      spreads: 0.05,
      afterG3: 0.06,
      afterG4: 0.06,
      fromBehindNeverTrail: 0.06
    }
  }
};

// Export for both browser global and Node.js require()
if (typeof module !== 'undefined' && module.exports) {
  module.exports = PLAYOFFS_DATA;
}
